NavBar Vers.1
TheAyes/GrosShop pull request #28
Opened 2023-06-27 13:45 UTC by ClaudioSUPERCODE

Rudimentäre NavBar

2023-06-27 14:01 UTC, TheAyes requested changes

2023-06-27 14:01 UTC, TheAyes commented on client/src/components/NavBar/NavBar.module.scss
> +        color: black;
Hier dann später auf die variablen umsteigen.

2023-06-27 14:18 UTC, ClaudioSUPERCODE commented on client/src/components/NavBar/NavBar.module.scss
> +                height: 65px;
vielen dank für den tipp sensei

2023-06-27 14:20 UTC, ClaudioSUPERCODE commented on client/src/components/NavBar/NavBar.module.scss
> +        color: black;
yes sir

2023-06-27 14:20 UTC, ClaudioSUPERCODE commented on client/src/components/NavBar/NavBar.module.scss
> +    }
nebeneffekte wollen wir nicht... böse

2023-06-28 12:15 UTC, TheAyes commented on client/src/pages/ItemList/item-list.jsx
> +=======
Dieses `<<<<< HEAD` ist kein valider code und sollte nicht hier sein.

2023-06-28 12:15 UTC, TheAyes commented on client/src/pages/ItemList/item-list.jsx
> +>>>>>>> origin/main
das hier genauso

2023-06-29 07:40 UTC, TheAyes requested changes

2023-06-29 07:40 UTC, TheAyes commented on client/src/components/NavBar/NavBar.module.scss
> +    width: 100vw;
Ist das nötig? Theoretisch müsste das eh die gesamte Breite einnehmen.

Ansonsten wären 100% ein bisschen eleganter
```suggestion
    width: 100%;
```

2023-06-29 07:40 UTC, TheAyes commented on client/src/components/NavBar/NavBar.module.scss
> +        text-decoration: none;
Ist global schon spezifiziert, also überflüssig. 
```suggestion
```

2023-06-29 07:40 UTC, TheAyes commented on client/src/components/NavBar/NavBar.module.scss
> +                padding-top: 0;
padding top 0 ? Ist doch sowieso immer auf null.
```suggestion
```

2023-06-29 07:56 UTC, TheAyes approved these changes

2023-06-29 07:56 UTC, merged